# Generated by Django 3.0 on 2019-12-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Creditos', models.PositiveSmallIntegerField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primer_Apellido', models.CharField(max_length=35)),
                ('Segundo_Apellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Cedula', models.CharField(max_length=8)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Matricula', models.DateTimeField(auto_now_add=True)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_Manager.Curso')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_Manager.Estudiante')),
            ],
        ),
    ]
